### ISSUE TITLE
Async problem with basicTypes.getBase64DecodingStream(input)

### ISSUE THREAD

**Issue by c-geek** [gnewpg/node-pgp#5]
Hi
First, congratulations for the accomplished work until there. Your code may save me a lot of time :)

However, trying to extract key information from ASCII-Armored key using this code:

```
var inBuffer = new Buffer(req.body.keytext);
var inStream = new pgp.BufferedStream(inBuffer);
pgp.formats.dearmor(inStream).readUntilEnd(function(err, data) {
    // ... Some code
}
```

I get the following error:

```
buffer.js:582
    throw new RangeError('Trying to access beyond buffer length');
          ^
RangeError: Trying to access beyond buffer length
    at checkOffset (buffer.js:582:11)
    at Buffer.readUInt16BE (buffer.js:616:5)
    at Object.readon [as callback] (/home/cgeek/dev/nodecoin/node_modules/node-pgp/basicTypes.js:275:54)
    at Object.BufferedStream.__checkRead (/home/cgeek/dev/nodecoin/node_modules/node-pgp/bufferedStream.js:62:8)
    at Object._onImmediate (/home/cgeek/dev/nodecoin/node_modules/node-pgp/utils.js:63:15)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

After few investigations, it seems that the issue comes from `getBase64DecodingStream` function which returns an empty BufferedStream (with property __buffer: Buffer[-1]), as it is initialized using I/O events).

Could you do anything about this please ?

**Comment by c-geek** [comment]
Ok I found my problem: as I was testing with Http Requester (Sublime Text plugin) which sent ASCII-Armored data without the '+' characters, hence having a corrupted message..
